export const MONTHLYSALES: Array<any> = [
      { name: 'Video Game',
        monthlySales: [
          {month: 'Jan', sales: 100},
          {month: 'Fev', sales: 232},
          {month: 'Mar', sales: 300},
          {month: 'Abr', sales: 250},
          {month: 'Mai', sales: 480},
          {month: 'Jun', sales: 600},
          {month: 'Jul', sales: 413},
          {month: 'Ago', sales: 510},
          {month: 'Set', sales: 700},
          {month: 'Out', sales: 860},
          {month: 'Nov', sales: 750},
          {month: 'Dec', sales: 890},
        ]
      },
      { name: 'Notebook',
        monthlySales: [
          {month: 'Jan', sales: 16},
          {month: 'Fev', sales: 19},
          {month: 'Mar', sales: 25},
          {month: 'Abr', sales: 35},
          {month: 'Mai', sales: 27},
          {month: 'Jun', sales: 22},
          {month: 'Jul', sales: 29},
          {month: 'Ago', sales: 30},
          {month: 'Set', sales: 42},
          {month: 'Out', sales: 55},
          {month: 'Nov', sales: 60},
          {month: 'Dec', sales: 53},
        ]
      },
      { name: 'Cellphone',
        monthlySales: [
          {month: 'Jan', sales: 35},
          {month: 'Fev', sales: 72},
          {month: 'Mar', sales: 120},
          {month: 'Abr', sales: 150},
          {month: 'Mai', sales: 110},
          {month: 'Jun', sales: 122},
          {month: 'Jul', sales: 135},
          {month: 'Ago', sales: 200},
          {month: 'Set', sales: 220},
          {month: 'Out', sales: 210},
          {month: 'Nov', sales: 210},
          {month: 'Dec', sales: 215},
        ]
      },
      { name: 'Tablet',
        monthlySales: [
          {month: 'Jan', sales: 100},
          {month: 'Fev', sales: 130},
          {month: 'Mar', sales: 135},
          {month: 'Abr', sales: 150},
          {month: 'Mai', sales: 170},
          {month: 'Jun', sales: 165},
          {month: 'Jul', sales: 180},
          {month: 'Ago', sales: 200},
          {month: 'Set', sales: 220},
          {month: 'Out', sales: 150},
          {month: 'Nov', sales: 135},
          {month: 'Dec', sales: 100},
        ]
      }
    ]